ARG NGINX_VERSION
FROM nginx:${NGINX_VERSION}

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./default.conf.template /etc/nginx/templates/default.conf.template

RUN apk add bash
WORKDIR /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
